version: "3"

services:
  # postgres:
  #   image: postgres:13.3
  #   ports:
  #     - "35500:5432"
  #   environment:
  #     POSTGRES_DB: "postgres"
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "postgres"

  trans_backend:
    build:
      dockerfile: backend-dockerfile
    expose:
      - ${APP_SERVER_PORT}
    # depends_on:
    #  - postgres
    volumes:
      - ./backend:/usr/src/transcendence
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_SERVER_HOST}
      API_SERVER_HOST: ${API_SERVER_HOST}
    command: npm run start:dev

  trans_frontend:
    build:
      dockerfile: frontend-dockerfile
    # depends_on:
    #   - trans_backend
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./frontend/src:/usr/src/transcendence/src
      - ./frontend/public:/usr/src/transcendence/public
    links:
      - trans_backend
    command: npm run start