version: "3.5"

services: 

  postgresql:
    restart: on-failure
    build:
      context: postgreSQL/
    image: mbonnet/postgresql
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      
  ourwebsite:
    restart: on-failure
    build:
      context: ourWebSite/
    image: mbonnet/ourwebsite
    container_name: ourwebsite

  nginx:
    restart: on-failure
    build:
      context: nginx/
    image : mbonnet/nginx
    container_name: nginx
    ports: 
      - "80:80"
      - "443:443"